dataset:
    name: SemanticKitti
    version: null
    path: /home/data/SemanticKitti
    rotate_aug: True  # todo
    flip_aug: True  # todo
    max_volume_space: [ 50, 3.1415926, 3 ]
    min_volume_space: [ 0, -3.1415926, -5 ]
    gt_generator:
        sigma: 5
    grid_size: [480,360,32]  # grids with polar coordinate
    inst_aug:
        if_use: True
        aug_type: contmix
        inst_pkl_path: /home/data/SemanticKitti/instance_path.pkl
        inst_trans: True # random translation for contmix
        inst_rotate: True
        inst_flip: True
        inst_add: True
    num_worker: 12
    min_points: 15
model:
    pix_fusion: True
    pix_fusion_path: checkpoints/resnet18-5c106cde.pth
    use_sara: True
    use_att: False  # gh todo
    use_cont: False  # gh todo
    model_load_path: kitti_ckpts
    model_save_path: kitti_ckpts
    train_batch_size: 4
    val_batch_size: 4
    learning_rate: 0.004
    LR_MILESTONES: [40, 60,90]
    LR_GAMMA: 0.5
    check_iter: 4000
    max_epoch: 120 # us 120 -> 0
    post_proc:
        threshold: 0.1
        nms_kernel: 5
        top_k: 100
    center_loss: MSE
    offset_loss: L1
    center_loss_weight: 100
    offset_loss_weight: 10
