# Config format schema number
format_version: 4

###################
## Model options
model_params:
  model_architecture: "cylinder_asym"

  output_shape:
    - 480
    - 360
    - 32

  fea_dim: 9
  out_fea_dim: 256
  num_class: 20
  num_input_features: 16
  use_norm: True
  init_size: 32


###################
## Dataset options
dataset_params:
  dataset_type: "cylinder_dataset"
  pc_dataset_type: "SemKITTI_sk"
  ignore_label: 0
  return_test: False
  fixed_volume_space: True
  label_mapping: "./configs/label_mapping/semantic-kitti.yaml" # us
  max_volume_space:
    - 50
    - 3.1415926
    - 2
  min_volume_space:
    - 0
    - -3.1415926
    - -4


###################
## Data_loader options
train_data_loader:
  data_path: "/home/data/SemanticKitti/dataset/sequences" # us
  imageset: "train"
  return_ref: True
  batch_size: 5
  shuffle: True
  num_workers: 4

val_data_loader:
  data_path: "/home/data/SemanticKitti/dataset/sequences" # us
  imageset: "val"
  return_ref: True
  batch_size: 1
  shuffle: False
  num_workers: 4


###################
## Train params
train_params:
  model_load_path: "./kitti_ckpts/kitti_late_concat_119epoch.pt" # us
  model_save_path: "./kitti_ckpts/model_save.pt" # us
  checkpoint_every_n_steps: 4599
  max_num_epochs: 0 # us
  eval_every_n_steps: 4599
  learning_rate: 0.001
  weight_decay: 0.001
  mixed_fp16: True
